public native void IsoTest_SetDialog(NpcDialogBox dbox);

public class NpcDialogBox {
	/** first frame of face sprite */
	public string face1;
	/** second frame of face sprite */
	public string face2;

	/** text for dialog box */
	public string text;
	public string[] options;
	public NpcDialogBox[] optchain;
	
	public void impulse(int imp)
	{
		frgl_printf("Diag Impulse %d\n", imp);
		
		if((imp>0) && optchain)
		{
			IsoTest_SetDialog(optchain[imp-1]);
		}
	}
}
