#include "vox_chunk.c"
#include "vox_decrice.c"
#include "vox_draw.c"
#include "vox_drawent.c"
#include "vox_light.c"
#include "vox_load.c"
#include "vox_mesh.c"
#include "vox_rice.c"
#include "vox_save.c"
#include "vox_tick.c"
#include "vox_trace.c"
#include "vox_voxty.c"
#include "vox_world.c"

#include "vox_tg_mare.c"

#include "../entity/ent_bsvm.c"
#include "../entity/ent_dialog.c"
