/* Autogenerated header */

#define BASM_OP_ARM_BX_C				0
#define BASM_OP_ARM_B_C					1
#define BASM_OP_ARM_BL_C				2
#define BASM_OP_ARM_AND_CS				3
#define BASM_REG_ARM_R0					32
#define BASM_REG_ARM_R1					33
#define BASM_REG_ARM_R2					34
#define BASM_REG_ARM_R3					35
#define BASM_REG_ARM_R4					36
#define BASM_REG_ARM_R5					37
#define BASM_REG_ARM_R6					38
#define BASM_REG_ARM_R7					39
#define BASM_REG_ARM_R8					40
#define BASM_REG_ARM_R9					41
#define BASM_REG_ARM_R10				42
#define BASM_REG_ARM_R11				43
#define BASM_REG_ARM_R12				44
#define BASM_REG_ARM_R13				45
#define BASM_REG_ARM_R14				46
#define BASM_REG_ARM_R15				47
#define BASM_REG_ARM_SP					45
#define BASM_REG_ARM_LR					46
#define BASM_REG_ARM_PC					47
