BUILD=.
MKSUF=.lnx
LIBSUF=.a
DLLSUF=.so
EXESUF=.elf
OBJSUF=.o
DLLPF=lib

CC_OUTEXE=gcc -o 
CC_OUTDLL=gcc -shared -o 
CC_OUTOBJ=gcc -c -o 
CC_OUTTOOL=gcc -o 

EXESUF = .elf
BINSUF = .bin
O = .o
A = .a

CFLAGS=-Iinclude -g -pg
DLL_CFLAGS=$(CFLAGS) -DBGBASM_DLL
DLL_LDFLAGS=-ldl -fPIC \
	-Wl,-rpath,"$$ORIGIN"
LDFLAGS=-g -pg -L. -lbgbasm -fPIC \
	-Wl,-rpath,"$$ORIGIN"

include Makefile.inc

