/* Autogenerated source */

#include <stdio.h>

char *basm_ops_arm[]={
"bx.c", "b.c", "bl.c", "and.cs", NULL};

int basm_opidx_arm[]={
0, 1, 2, 3, -1};

int basm_opnums_arm[]={
0, 1, 2, 3, 3, -1};

char basm_opcat_arm[]={
22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 22, 22, 22, 92, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
22, 22, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

char *basm_opdecl_arm[]={
"Gz012FFF10|ra", "Gz0A000000|ia", "Gz0A000000|ia", "Gc00000000|rd|re|ra|is", 
"Gc02000000|rd|re|irb", NULL};

char *basm_regs_arm[]={
"r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", 
"r11", "r12", "r13", "r14", "r15", "sp", "lr", "pc", NULL};

int basm_regidx_arm[]={
32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 45, 
46, 47, -1};

